arucos:
  - id: 30
    position:
      x: 7.0
      y: 3.5
  - id: 31
    position:
      x: 3.5
      y: 7.0
  - id: 32
    position:
      x: 0.0
      y: 3.5
  - id: 33
    position:
      x: 3.5
      y: 0.0