arucos:
  - id: 31
    position:
      x: 0.0
      y: 0.0
  - id: 32
    position:
      x: 1.0
      y: 1.0
  - id: 33
    position:
      x: 2.0
      y: 2.0
  - id: 34
    position:
      x: 3.0
      y: 3.0