waypoints:
  - {id: 1, 'x': -3.0, 'y': 3.0, 'yaw': 0.0},
  - {id: 2, 'x': 3.0, 'y': -3.0, 'yaw': 0.0},
  - {id: 3, 'x': 3.0, 'y': 3.0, 'yaw': 0.0},
  - {id: 4, 'x': -3.0, 'y': -3.0, 'yaw': 0.0},
  - {id: 5, 'x': 0.0, 'y': 0.0, 'yaw': 0.0},
